# © 2025 Little Shilling, Inc.
# Shon Little
# Created: 2025-05-12

server {
  listen 80;
  server_name shonlittle.com;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}
